### ISSUE TITLE
support libstdc++

### ISSUE THREAD

**Issue by sluongng** [bazel-contrib/musl-toolchain#15]
From https://www.musl-libc.org/faq.html

> Be aware that, "out of the box", the wrapper only supports C applications, not C++. This is because the C++ libraries and headers are missing from the musl include/library path. The existing libstdc++ is actually compatible with musl in most cases and could be used by copying it into the musl library path, but the C++ header files are usually not compatible. One option may be rebuilding just libstdc++ against musl; however, if C++ support is needed, it's recommended just to build a native toolchain targetting musl.

Currently when using this toolchain to build some cc_binary, such as `protoc`, I would get this error when trying to run the output artifact:

```
exec bazel-out/linux_x86_64-opt-exec/bin/external/com_google_protobuf/protoc: no such file or directory
```

which suggests that the libstdc++ was dynamically linked and err-out because it's not available at runtime.

**Comment by fmeum** [comment]
`fully_static_link` has been enabled by default.

**Comment by gibfahn** [comment]
(in https://github.com/bazel-contrib/musl-toolchain/pull/22)
