### ISSUE TITLE
Build fails missing `libisl` when `/usr/local` is blocked from sandbox access on MacOS x86_64

### ISSUE THREAD

**Issue by akesling** [bazel-contrib/musl-toolchain#25]
# Observed behavior
Build fails on MacOS, complaining of `libisl` not being available under `/usr/local` when `--sandbox_block_path=/usr/local` is provided to `build` command.  See https://gist.github.com/akesling/2b2d059cd6fc1e5257026e562b7f933a for build error output.

Note that `--sandbox_block_path=/usr/local` helps mitigate non-hermetic library inclusion on MacOS.  See https://github.com/bazelbuild/bazel/issues/10472#issuecomment-6785287 for context.

# Reproduction
See [musl-isl-repro branch in reproduction repo](https://github.com/akesling/cgo_repro/tree/musl-isl-repro) for a full reproduction.

## Steps
1) Include `musl-toolchain` in WORKSPACE
2) Add `build --sandbox_block_path=/usr/local` to `.bazelrc`
3) Configure a build transition for `@io_bazel_rules_go//go/toolchain:linux_amd64_cgo`
4) Build cross-compiling target

**Comment by illicitonion** [comment]
This was fixed in https://github.com/bazel-contrib/musl-toolchain/pull/23 and released in 0.1.13 :)
